apiVersion: apps/v1
kind: Deployment
metadata:
  name: timescaledb
  namespace: agricultura
  labels:
    app: timescaledb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: timescaledb
  template:
    metadata:
      labels:
        app: timescaledb
    spec:
      nodeSelector:
        role: infra
      containers:
        - name: timescaledb
          image: timescale/timescaledb:2.14.2-pg16
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: timescaledb-secret
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
            - name: init-sql
              mountPath: /docker-entrypoint-initdb.d
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "admin", "-d", "agriculture"]
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            exec:
              command: ["pg_isready", "-U", "admin", "-d", "agriculture"]
            initialDelaySeconds: 20
            periodSeconds: 15
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "1"
              memory: "1Gi"
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: timescaledb-pvc
        - name: init-sql
          configMap:
            name: timescaledb-init
