apiVersion: apps/v1
kind: Deployment
metadata:
  name: processor
  namespace: agricultura
  labels:
    app: processor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: processor
  template:
    metadata:
      labels:
        app: processor
    spec:
      nodeSelector:
        role: apps
      initContainers:
        - name: wait-for-db
          image: busybox:1.36
          command:
            - sh
            - -c
            - |
              until nc -z timescaledb 5432; do
                echo "Esperando TimescaleDB..."; sleep 3
              done
              echo "TimescaleDB disponible."
        - name: wait-for-nats
          image: busybox:1.36
          command:
            - sh
            - -c
            - |
              until nc -z nats 4222; do
                echo "Esperando NATS..."; sleep 3
              done
              echo "NATS disponible."
      containers:
        - name: processor
          image: <tu-usuario>/agricultura-processor:latest
          imagePullPolicy: Always
          env:
            - name: NATS_URL
              value: "nats://nats:4222"
            - name: DB_HOST
              value: timescaledb
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: timescaledb-secret
                  key: POSTGRES_DB
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: timescaledb-secret
                  key: POSTGRES_USER
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: timescaledb-secret
                  key: POSTGRES_PASSWORD
            - name: MODEL_PATH
              value: /tmp/model.pkl
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
