apiVersion: 1

datasources:
  - name: TimescaleDB
    uid: timescaledb-ds
    type: postgres
    url: timescaledb:5432
    database: agriculture
    user: admin
    secureJsonData:
      password: $POSTGRES_PASSWORD
    jsonData:
      sslmode: disable
      postgresVersion: 1600
      timescaledb: true
    isDefault: true
    editable: false
