apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: agricultura
  labels:
    app: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      nodeSelector:
        role: infra
      containers:
        - name: grafana
          image: grafana/grafana:10.3.3
          ports:
            - containerPort: 3000
          env:
            - name: GF_SECURITY_ADMIN_USER
              value: admin
            - name: GF_SECURITY_ADMIN_PASSWORD
              value: admin
            - name: GF_USERS_ALLOW_SIGN_UP
              value: "false"
            - name: GF_AUTH_ANONYMOUS_ENABLED
              value: "false"
          volumeMounts:
            - name: provisioning
              mountPath: /etc/grafana/provisioning/datasources/datasource.yaml
              subPath: datasource.yaml
            - name: provisioning
              mountPath: /etc/grafana/provisioning/dashboards/dashboard-provider.yaml
              subPath: dashboard-provider.yaml
            - name: provisioning
              mountPath: /etc/grafana/provisioning/dashboards/sensores.json
              subPath: sensores.json
            - name: grafana-data
              mountPath: /var/lib/grafana
          readinessProbe:
            httpGet:
              path: /api/health
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 10
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
      volumes:
        - name: provisioning
          configMap:
            name: grafana-provisioning
        - name: grafana-data
          persistentVolumeClaim:
            claimName: grafana-pvc
